### ISSUE TITLE
Update generators to use new `ember-test-utils>=2`

### ISSUE THREAD

**Issue by job13er** [ciena-frost/ember-frost-test#18]
The new version of `ember-test-utils` utilizes `addon-test-support/` and so the mechanism for importing the test helpers has changed with that version. We should update the blueprints/dependencies here as well as the generators.

We can/should probably move the dependency on `ember-test-utils` from `blueprints/` to `dependencies` in `package.json` as well.

**Comment by juwara0** [comment]
Since the blueprint generators have been moved to `ember-cli-frost-blueprints`, I believe this issue can be closed.

**Comment by notmessenger** [comment]
With the previous comment and PR https://github.com/ciena-frost/ember-frost-test/pull/40 I am closing this issue.
